import catalog from './catalog.json';
import type { Locale } from './types';

const extra: Record<string, [string, string]> = {
  'nav.harbor': ['The harbor', 'Гавань'], 'nav.learn': ['How to play', 'Как играть'], 'nav.logbook': ['Your logbook', 'Ваш журнал'],
  'hero.eyebrow': ['A QUIET COOPERATIVE ADVENTURE', 'ТИХОЕ СОВМЕСТНОЕ ПРИКЛЮЧЕНИЕ'],
  'hero.title': ['A little harbor.', 'Маленькая гавань.'], 'hero.title2': ['A shared purpose.', 'Общее дело.'],
  'hero.description': ['A parcel to deliver. A route only you know. Find your way together, one small signal at a time.', 'Посылка ждёт доставки. Только вы знаете маршрут. Находите путь вместе, обмениваясь маленькими сигналами.'],
  'hero.footnote': ['Free to play. No chat needed. Just a little understanding.', 'Бесплатно. Без чата. С небольшим взаимопониманием.'],
  'hero.stamp': ['SMALL SIGNALS. SHARED VICTORIES.', 'МАЛЕНЬКИЕ СИГНАЛЫ. ОБЩИЕ ПОБЕДЫ.'],
  'meta.players': ['2–4 friends', '2–4 друга'], 'meta.time': ['A few quiet minutes', 'Несколько тихих минут'], 'meta.private': ['Your own private crew', 'Только ваша команда'],
  'home.harbors': ['Find your next harbor', 'Найдите свою гавань'], 'home.harborsDescription': ['Ten little places. A different way to work together.', 'Десять маленьких мест. Новые способы работать вместе.'],
  'home.allMaps': ['Explore all 10', 'Все 10 гаваней'], 'home.fewerMaps': ['Show fewer', 'Свернуть'],
  'home.how': ['Different plans. One good shift.', 'Разные планы. Одна хорошая смена.'],
  'home.howDescription': ['You don’t need all the answers. Just enough to help each other.', 'Не обязательно знать все ответы. Достаточно помогать друг другу.'],
  'how.card': ['Your parcel, your secret', 'Ваша посылка, ваш секрет'], 'how.cardText': ['Two berths can take your parcel. Only you see which ones.', 'Два причала могут принять посылку. Только вы знаете какие.'],
  'how.signal': ['Say a little', 'Скажите немного'], 'how.signalText': ['Leave one signal on the chart. A request, never a reservation.', 'Оставьте один сигнал на карте. Это просьба, а не бронь.'],
  'how.move': ['Move together', 'Двигайтесь вместе'], 'how.moveText': ['Commit your route. Every 20 seconds, the whole harbor moves.', 'Подтвердите маршрут. Каждые 20 секунд вся гавань движется.'],
  'footer.copy': ['A small harbor. A private promise.', 'Маленькая гавань. Личное обещание.'],
  'dev.label': ['Development preview', 'Предварительная версия'], 'dev.description': ['Local test identities · purchases disabled', 'Тестовые профили · покупки отключены'],
  'practice.title': ['A little practice, together.', 'Немного практики вместе.'], 'practice.description': ['Meet your clearly labeled bot crew. The same harbor rules, with room to learn.', 'Познакомьтесь с командой ботов. Те же правила гавани и возможность учиться.'],
  'practice.crew': ['Choose your crew', 'Выберите команду'], 'practice.one': ['You + 1 bot', 'Вы + 1 бот'], 'practice.two': ['You + 2 bots', 'Вы + 2 бота'], 'practice.three': ['You + 3 bots', 'Вы + 3 бота'],
  'practice.timing': ['Set your pace', 'Выберите темп'], 'practice.standard': ['Standard shift', 'Обычная смена'], 'practice.standardText': ['20-second rounds. Shared moves. Practice mastery.', 'Раунды по 20 секунд. Общие ходы. Мастерство тренировки.'], 'practice.untimedText': ['One bot. Advance when you commit. No mastery or ranking.', 'Один бот. Ход после подтверждения. Без мастерства и рейтинга.'],
  'practice.start': ['Set sail', 'Отчалить'], 'map.choose': ['Choose a harbor', 'Выберите гавань'], 'map.hint': ['A note from the harbormaster', 'Совет смотрителя гавани'],
  'friends.title': ['Good company. Quiet waters.', 'Хорошая компания. Тихие воды.'], 'friends.description': ['Create an invite-only room and bring your crew aboard.', 'Создайте закрытую комнату и пригласите команду.'], 'friends.create': ['Create private room', 'Создать закрытую комнату'], 'friends.capacity': ['Crew capacity', 'Размер команды'],
  'room.you': ['You', 'Вы'], 'room.empty': ['A place for a friend', 'Место для друга'], 'room.waiting': ['Waiting for your crew', 'Ждём вашу команду'], 'room.shareText': ['Only people with your invitation can join. Links expire after 30 minutes.', 'Войти можно только по приглашению. Ссылка действует 30 минут.'], 'room.waitingPlayer': ['Invite another captain to begin.', 'Пригласите ещё одного капитана.'],
  'room.readyText': ['Read the chart. Ready when you are.', 'Изучите карту. Подтвердите готовность.'], 'room.starting': ['All aboard. Preparing your shift…', 'Все на борту. Готовим смену…'],
  'game.chart': ['Harbor chart', 'Карта гавани'], 'game.crew': ['On the water', 'На воде'], 'game.routes': ['Follow the arrows', 'Следуйте стрелкам'], 'game.node': ['Junction', 'Узел'], 'game.entry': ['Home dock', 'Домашний причал'], 'game.empty': ['Open water', 'Свободно'], 'game.outgoing': ['Outgoing routes', 'Исходящие маршруты'], 'game.select': ['Select {node}', 'Выбрать {node}'], 'game.inspect': ['Inspect {node}', 'Осмотреть {node}'],
  'game.parcel': ['Your delivery', 'Ваша доставка'], 'game.cargo': ['A little something, eagerly awaited.', 'Маленькая посылка, которую очень ждут.'], 'game.or': ['or', 'или'], 'game.signal': ['Leave a signal', 'Оставьте сигнал'], 'game.signalNone': ['No signal placed', 'Сигнал не установлен'], 'game.signalTarget': ['Now choose a node on the chart or list.', 'Теперь выберите узел на карте или в списке.'], 'game.yourRoute': ['Your next move', 'Ваш следующий ход'], 'game.waitHelp': ['Staying put can make room for someone else.', 'Ожидание может освободить путь другому.'],
  'game.deliveries': ['Deliveries', 'Доставки'], 'game.congestion': ['Congestion', 'Заторы'], 'game.round': ['Round', 'Раунд'], 'game.time': ['Time left', 'Осталось'], 'game.untimed': ['No timer', 'Без таймера'],
  'game.deliveryEvent': ['The harbor moved. Parcels delivered: {count}.', 'Гавань пришла в движение. Доставлено посылок: {count}.'], 'game.readOnly': ['Read-only. Request control for the next round.', 'Режим просмотра. Запросите управление на следующий раунд.'],
  'result.title': ['A good evening’s work.', 'Хорошая вечерняя работа.'], 'result.timeline': ['The story of your shift', 'История вашей смены'], 'result.back': ['Back to the harbor', 'Вернуться в гавань'], 'result.shared': ['Team result copied', 'Результат команды скопирован'],
  'settings.description': ['Make yourself at home.', 'Устраивайтесь поудобнее.'], 'settings.display': ['Display & accessibility', 'Отображение и доступность'], 'settings.audio': ['Sound & atmosphere', 'Звуки и атмосфера'],
  'help.title': ['A small guide to shared waters.', 'Небольшой путеводитель по общим водам.'], 'help.goal': ['Deliver 6 parcels in 8 rounds, before congestion reaches 5.', 'Доставьте 6 посылок за 8 раундов, пока заторы не достигли 5.'], 'help.conflict': ['Two boats choosing the same node both stay, adding one congestion point. A direct swap also adds one. Following a departing boat is allowed; waiting behind a stationary boat adds no congestion.', 'Если два судна выбирают один узел, оба остаются и добавляется один затор. Встречный обмен тоже добавляет один. Следовать за уходящим судном можно; ожидание за стоящим не добавляет заторов.'],
  'help.private': ['Your job and unplayed route stay private. Signals are public, advisory, and never reserve a node. READY is a signal, not a route commitment.', 'Ваша задача и будущий маршрут скрыты. Сигналы видны всем, но не резервируют узел. READY — сигнал, а не подтверждение хода.'],
  'help.score': ['Team score = 20 × deliveries + 5 × preferred deliveries − 4 × congestion, never below zero. Congestion is checked before success.', 'Очки команды = 20 × доставки + 5 × предпочтительные доставки − 4 × заторы, не ниже нуля. Предел заторов проверяется раньше успеха.'],
  'learn.title': ['Let’s find our sea legs.', 'Давайте освоимся.'], 'learn.next': ['Try the next step', 'Следующий шаг'], 'learn.question': ['Six deliveries and five congestion. Is the shift successful?', 'Шесть доставок и пять заторов. Смена успешна?'], 'learn.yes': ['Yes, six arrived', 'Да, шесть доставлены'], 'learn.no': ['No, congestion comes first', 'Нет, заторы проверяются первыми'], 'learn.correct': ['Exactly. Congestion is checked first. A new shift is another chance.', 'Верно. Заторы проверяются первыми. Новая смена — новый шанс.'], 'learn.wrong': ['Almost! Congestion is checked before deliveries. Five congestion ends the shift.', 'Почти! Заторы проверяются раньше доставок. Пять заторов завершают смену.'], 'learn.start': ['Try an untimed harbor', 'Попробовать без таймера'],
  'logbook.title': ['Your harbor logbook', 'Ваш журнал гавани'], 'logbook.description': ['Small moments of understanding, worth remembering.', 'Маленькие моменты понимания, которые стоит помнить.'], 'logbook.empty': ['Your first light is still ahead.', 'Ваш первый огонёк ещё впереди.'], 'logbook.emptyText': ['Finish a successful standard shift to begin your collection. Practice and human-only mastery stay separate.', 'Завершите успешную обычную смену, чтобы начать коллекцию. Мастерство с игроками и ботами учитывается отдельно.'], 'logbook.first': ['First Light', 'Первый огонёк'], 'logbook.familiar': ['Familiar Waters', 'Знакомые воды'], 'logbook.keeper': ['Harbor Keeper', 'Хранитель гавани'], 'logbook.distinct': ['Distinct successful scenarios', 'Разные успешные сценарии'],
  'safety.title': ['Keep the harbor welcoming', 'Сохраним гавань дружелюбной'], 'safety.category': ['What would you like to report?', 'О чём вы хотите сообщить?'], 'safety.technical': ['Technical problem', 'Техническая проблема'], 'safety.name': ['Inappropriate display name', 'Неподходящее имя'], 'safety.harassment': ['Harassment', 'Оскорбления'], 'safety.other': ['Other product problem', 'Другая проблема'], 'safety.submit': ['Submit report', 'Отправить сообщение'], 'safety.noPrivate': ['Only a public scenario reference is attached. Do not include private messages or payment secrets.', 'Прилагается только ссылка на общедоступные события смены. Не указывайте личные сообщения и платёжные секреты.'],
  'privacy.title': ['Your privacy matters', 'Ваша конфиденциальность важна'], 'privacy.text': ['Jobs and sealed routes are visible only to their owner. No ads, chat, wallets, or public profiles. Reports are stored for operator review; this development preview does not have a staffed support service. Public launch requires operator privacy and support details.', 'Задачи и выбранные маршруты видны только владельцу. Без рекламы, чата, кошельков и публичных профилей. Сообщения сохраняются для проверки оператором; в предварительной версии нет службы поддержки. Для запуска нужны сведения об операторе и поддержке.'],
  'licenses.text': ['This preview uses original procedural raster artwork and synthesized audio. The specified commissioned/generated illustration package remains a release gate. Golos Text is distributed under the SIL Open Font License. See the asset manifest and licenses included with the source.', 'В этой версии используются оригинальные процедурные растровые иллюстрации и синтезированное аудио. Финальный художественный пакет ещё необходим для выпуска. Шрифт Golos Text распространяется по SIL Open Font License. Манифест и лицензии включены в исходный код.'],
  'common.close': ['Close', 'Закрыть'], 'common.saved': ['Saved', 'Сохранено'], 'common.loading': ['A moment…', 'Минутку…'],
  'error.generic': ['The harbor could not confirm that action. Please try again.', 'Гавань не подтвердила действие. Попробуйте ещё раз.'],
};

export function translate(locale: Locale, key: string, args: Record<string, string | number> = {}) {
  if (key === 'hud.seconds' && typeof args.count === 'number') {
    const form = new Intl.PluralRules(locale).select(args.count);
    if (locale === 'en') return `${args.count} ${form === 'one' ? 'second' : 'seconds'} left`;
    return `${form === 'one' ? 'Осталась' : 'Осталось'} ${args.count} ${form === 'one' ? 'секунда' : form === 'few' ? 'секунды' : 'секунд'}`;
  }
  const base = (catalog[locale] as Record<string, string>)[key] ?? extra[key]?.[locale === 'en' ? 0 : 1] ?? key;
  return base.replace(/\{(\w+)\}/g, (_, k: string) => String(args[k] ?? `{${k}}`));
}
